import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F3F6FA',
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  title: {
    fontSize: 36,
    fontWeight: '700',
    color: '#1C2430',
    marginBottom: 18,
  },
  card: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 24,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#1A2332',
    shadowOpacity: 0.06,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#F26B5B',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1C2430',
  },
  count: {
    fontSize: 14,
    color: '#98A2B3',
  },
  addRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F5F8',
    borderRadius: 14,
    paddingLeft: 14,
    paddingRight: 6,
    marginTop: 14,
    marginBottom: 8,
  },
  addInput: {
    flex: 1,
    paddingVertical: 12,
    fontSize: 15,
    color: '#1C2430',
  },
  iconButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  list: {
    flex: 1,
  },
  item: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#fff',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#EEF1F5',
    paddingVertical: 10,
    paddingLeft: 12,
    paddingRight: 6,
    marginTop: 10,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: '#D0D5DD',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    backgroundColor: '#2FCB8A',
    borderColor: '#2FCB8A',
  },
  itemInput: {
    flex: 1,
    fontSize: 16,
    color: '#1C2430',
    paddingVertical: 2,
  },
  itemText: {
    flex: 1,
    fontSize: 16,
    color: '#2C3440',
  },
  completed: {
    flex: 1,
    fontSize: 16,
    color: '#9AA3AF',
    textDecorationLine: 'line-through',
  },
  error: {
    color: '#E15B64',
    marginBottom: 8,
  },
});
